package io.github.cascade.cache.v2.support;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.net.InetAddress;
import java.util.concurrent.atomic.AtomicBoolean;

/**
 * NodeId管理器 - 统一管理节点的唯一标识
 * <p>
 * 职责：
 * 1. 确保同一个JVM进程中的所有组件使用相同的NodeId
 * 2. 提供稳定可靠的NodeId生成算法
 * 3. 支持外部配置自定义NodeId
 * 4. 提供NodeId的缓存和单例管理
 * <p>
 * 设计原理：
 * - 单例模式：确保整个应用只有一个NodeId实例
 * - 懒加载：在首次使用时生成NodeId
 * - 可配置：支持通过系统属性或环境变量自定义
 * - 稳定性：一旦生成，在JVM生命周期内保持不变
 *
 * @author lionel lionelk@163.com
 * =============================
 * Date: 2025/10/30
 * Time: 01:05
 * =============================
 */
public class NodeIdManager {

    private static final Logger LOGGER = LoggerFactory.getLogger(NodeIdManager.class);

    // 单例实例
    private static volatile NodeIdManager instance;
    private static final Object LOCK = new Object();

    // 配置属性键
    private static final String NODE_ID_PROPERTY = "cascade.node.id";
    private static final String SPRING_APP_NAME_PROPERTY = "spring.application.name";
    private static final String DEFAULT_APP_NAME = "cascade-cache";

    // 缓存的NodeId
    private final String nodeId;
    private final AtomicBoolean initialized = new AtomicBoolean(false);

    /**
     * 私有构造函数
     */
    private NodeIdManager() {
        this.nodeId = generateNodeId();
        this.initialized.set(true);
        LOGGER.info("NodeIdManager初始化完成: nodeId={}", nodeId);
    }

    /**
     * 获取单例实例
     */
    public static NodeIdManager getInstance() {
        if (instance == null) {
            synchronized (LOCK) {
                if (instance == null) {
                    instance = new NodeIdManager();
                }
            }
        }
        return instance;
    }

    /**
     * 获取当前节点的唯一标识
     *
     * @return 节点ID，格式：[appName]-[hostname]-[pid]-[startupHash]
     */
    public String getNodeId() {
        if (!initialized.get()) {
            throw new IllegalStateException("NodeIdManager未正确初始化");
        }
        return nodeId;
    }

    /**
     * 生成唯一的节点ID
     * <p>
     * 生成策略：
     * 1. 优先使用系统属性 cascade.node.id
     * 2. 其次使用环境变量 CASCADE_NODE_ID
     * 3. 最后自动生成：[appName]-[hostname]-[pid]-[startupHash]
     *
     * @return 节点ID
     */
    private String generateNodeId() {
        // 1. 检查系统属性配置
        String configuredNodeId = System.getProperty(NODE_ID_PROPERTY);
        if (configuredNodeId != null && !configuredNodeId.trim().isEmpty()) {
            LOGGER.info("使用系统属性配置的NodeId: {}", configuredNodeId);
            return configuredNodeId.trim();
        }

        // 2. 检查环境变量配置
        String envNodeId = System.getenv("CASCADE_NODE_ID");
        if (envNodeId != null && !envNodeId.trim().isEmpty()) {
            LOGGER.info("使用环境变量配置的NodeId: {}", envNodeId);
            return envNodeId.trim();
        }

        // 3. 自动生成NodeId
        String autoGeneratedNodeId = generateAutoNodeId();
        LOGGER.info("自动生成的NodeId: {}", autoGeneratedNodeId);
        return autoGeneratedNodeId;
    }

    /**
     * 自动生成NodeId
     *
     * @return 自动生成的NodeId
     */
    private String generateAutoNodeId() {
        try {
            // 获取应用名称
            String appName = System.getProperty(SPRING_APP_NAME_PROPERTY, DEFAULT_APP_NAME);

            // 获取主机名
            String hostName = InetAddress.getLocalHost().getHostName();

            // 获取进程ID
            String pid = ProcessHandle.current().pid() + "";

            // 生成启动哈希（确保同一进程每次启动的哈希不同，但运行期间保持不变）
            String startupHash = generateStartupHash();

            // 组合NodeId
            String nodeId = String.format("%s-%s-%s-%s",
                    sanitize(appName),
                    sanitize(hostName),
                    pid,
                    startupHash);

            return nodeId;

        } catch (Exception e) {
            LOGGER.warn("自动生成NodeId失败，使用fallback方案", e);
            return generateFallbackNodeId();
        }
    }

    /**
     * 生成启动哈希
     * <p>
     * 使用启动时间和随机数生成哈希，确保：
     * - 同一进程的不同启动有不同的哈希
     * - 同一进程的运行期间哈希保持不变
     *
     * @return 启动哈希
     */
    private String generateStartupHash() {
        long startupTime = System.currentTimeMillis();
        int random = System.identityHashCode(this);
        int hash = (int) (startupTime ^ random);
        return Integer.toHexString(Math.abs(hash));
    }

    /**
     * 生成fallback NodeId（当自动生成失败时使用）
     *
     * @return fallback NodeId
     */
    private String generateFallbackNodeId() {
        String appName = System.getProperty(SPRING_APP_NAME_PROPERTY, DEFAULT_APP_NAME);
        long timestamp = System.currentTimeMillis();
        int random = (int) (Math.random() * 10000);
        return String.format("%s-fallback-%d-%d", sanitize(appName), timestamp, random);
    }

    /**
     * 清理字符串，确保NodeId的安全性
     *
     * @param input 输入字符串
     * @return 清理后的字符串
     */
    private String sanitize(String input) {
        if (input == null) {
            return "unknown";
        }
        // 替换不安全的字符
        return input.replaceAll("[^a-zA-Z0-9\\-_]", "-");
    }

    /**
     * 重置NodeId管理器（主要用于测试）
     */
    static void reset() {
        synchronized (LOCK) {
            instance = null;
        }
    }

    /**
     * 检查NodeId管理器是否已初始化
     *
     * @return 是否已初始化
     */
    public boolean isInitialized() {
        return initialized.get();
    }

    @Override
    public String toString() {
        return String.format("NodeIdManager{nodeId='%s', initialized=%s}",
                nodeId, initialized.get());
    }
}